# -*- coding: utf-8 -*-
"""
/***************************************************************************
 deltaforceDialog
                                 A QGIS plugin
 exports every single feature in a shapefile
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-07-24
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Olivier Pompier
        email                : ol.pompier@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.core import *

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'deltaforce_dialog_base.ui'))


class deltaforceDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(deltaforceDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.mMapLayerComboBox.layerChanged.connect(self.getLayer)
        self.mMapLayerComboBox.layerChanged.connect(self.populateFb)
        self.mMapLayerComboBox.layerChanged.connect(self.EnableOk)
        self.mFieldComboBox.fieldChanged.connect(self.getField)
        self.mFieldComboBox.fieldChanged.connect(self.EnableOk)
        self.toolButton.clicked.connect(self.getOpenFileName)
        self.toolButton.clicked.connect(self.EnableOk)
        self.button_box.button(QtWidgets.QDialogButtonBox.Ok).setEnabled(False)

    def getLayer(self):
        self.mMapLayerComboBox.currentLayer()

    def getPathSortie(self):
        self.mQgsFileWidget_sortie.filePath()

    def getField(self):
        self.mFieldComboBox.currentField()

    def populateFb(self):
        self.mFieldComboBox.setLayer(self.mMapLayerComboBox.currentLayer())

    def getOpenFileName(self):
        fn = QtWidgets.QFileDialog.getExistingDirectory(self,'Open File')
        self.lineEdit.setText(fn)

    def EnableOk(self):
        if os.path.exists(self.lineEdit.text()):
            self.button_box.button(QtWidgets.QDialogButtonBox.Ok).setEnabled(True)
        else:
            self.button_box.button(QtWidgets.QDialogButtonBox.Ok).setEnabled(False)



